name: GH Token Self Test

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Show gh version
        run: gh --version
      - name: Authenticate gh with GH_TOKEN
        run: echo "${GH_TOKEN}" | gh auth login --with-token
      - name: Whoami + rate limit
        run: |
          gh auth status
          gh api rate_limit