name: Add Secrets to SaaS Repositories

on:
  workflow_dispatch:
    inputs:
      vercel_token:
        description: 'VERCEL Token'
        required: true

jobs:
  add-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Add Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ github.event.inputs.vercel_token }}
        run: |
          for i in $(seq -f "SaaS-%02g" 1 20); do
            echo "Adding secrets to $i"
            gh repo edit "$i" --add-secret VERCEL_TOKEN "$VERCEL_TOKEN"
          done
