name: Add Secrets to SaaS Repositories

on:
  workflow_dispatch:
    inputs:
      vercel_token:
        description: "Paste your Vercel token (will be written as VERCEL_TOKEN in each SaaS repo)"
        required: true

jobs:
  add-secrets:
    runs-on: ubuntu-latest

    # Classic token with `repo` scope that you saved as a secret in the hub repo
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    strategy:
      fail-fast: false
      matrix:
        repo:
          - SaaS-01
          - SaaS-02
          - SaaS-03
          - SaaS-04
          - SaaS-05
          - SaaS-06
          - SaaS-07
          - SaaS-08
          - SaaS-09
          - SaaS-10
          - SaaS-11
          - SaaS-12
          - SaaS-13
          - SaaS-14
          - SaaS-15
          - SaaS-16
          - SaaS-17
          - SaaS-18
          - SaaS-19
          - SaaS-20

    steps:
      - name: Authenticate gh with GH_TOKEN
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh auth status

      - name: Add VERCEL_TOKEN to ${{ matrix.repo }}
        run: |
          echo "${{ github.event.inputs.vercel_token }}" \
          | gh secret set VERCEL_TOKEN \
              --repo Jvryan92/${{ matrix.repo }} \
              --app actions
